### ISSUE TITLE
Storyboards enum generation can be incomplete depending of the xml structure of storyboard file

### ISSUE THREAD

**Issue by QuentinArnault** [SwiftGen/SwiftGenKit#17]
Hi,

With this version
```
swiftgen --version
SwiftGen v0.0 (Stencil v0.8.0, StencilSwiftKit v1.0.0, SwiftGenKit v1.0.1)
```

I encountered a problem while generating storyboards enum: all instantiateXXXX functions were not generated.

After some investigation, it appears that the xml structure can impact generation of swift code.
I have two Storyboards, they are identical when viewed on Xcode but swiftgen produces this result

 
```enum StoryboardScene {
  enum LoginWithSupportedXML: String, StoryboardSceneType {
    static let storyboardName = "LoginWithSupportedXML"

    case totoScene = "toto"
    static func instantiateToto() -> UIViewController {
      return StoryboardScene.LoginWithSupportedXML.totoScene.viewController()
    }
  }
  enum LoginWithUnsupportedXML: StoryboardSceneType {
    static let storyboardName = "LoginWithUnsupportedXML"
  }
}
```

The only difference between this two files is the order of the `placeholder` XML element. If it is before `viewController` element it does not work, if it is after, it works.

[Storyboards.zip](https://github.com/SwiftGen/SwiftGenKit/files/858251/Storyboards.zip)

**Comment by AliSoftware** [comment]
Just to be able to understand the issue without having to unzip the file, from what Quentin explained to me here's a little extract of the difference he saw:

This doesn't work (the generated file doesn't list any scene):
```swift
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<document …>
    …
    <scenes>
        <!--View Controller-->
        <scene sceneID="wIf-mi-pQb">
            <objects>
                <placeholder placeholderIdentifier="IBFirstResponder" id="2NF-ea-wdU" userLabel="First Responder" sceneMemberID="firstResponder"/>
                <viewController storyboardIdentifier="toto" id="345-Bl-j59" sceneMemberID="viewController">
                    …
                </viewController>
            </objects>
            <point key="canvasLocation" x="992" y="1339"/>
        </scene>
    </scenes>
</document>
```

But this does work as expected:
```swift
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<document …>
    …
    <scenes>
        <!--View Controller-->
        <scene sceneID="wIf-mi-pQb">
            <objects>
                <viewController storyboardIdentifier="toto" id="345-Bl-j59" sceneMemberID="viewController">
                    …
                </viewController>
            <placeholder placeholderIdentifier="IBFirstResponder" id="2NF-ea-wdU" userLabel="First Responder" sceneMemberID="firstResponder"/></objects>
            <point key="canvasLocation" x="992" y="1339"/>
        </scene>
    </scenes>
</document>
```

**Comment by djbe** [comment]
The DOM parser (#18) fixes this for me, I tried it with the storyboards files you attached.

If you're up to it, you could check out the project and run a test version on your storyboard files. You'll have to clone SwiftGen and change the Podfile to point to SwiftGenKit like this:
```  pod 'SwiftGenKit', :git => 'git@github.com:SwiftGen/SwiftGenKit.git', :branch => 'feature/new-xml-parser'```
Then either run using Xcode (change the launch arguments), or build (and install) using `rake`.
