### ISSUE TITLE
Code generation from JSON data

### ISSUE THREAD

**Issue by Liquidsoul** [SwiftGen/SwiftGenKit#30]
## Introduction

This issue is a follow up for the PR https://github.com/SwiftGen/SwiftGen/pull/188

The objective is to have a way to describe a context using JSON file(s) that will be run against a (and if possible multiple) stencil file(s) to generate Swift code.

## Motivation

Right now, `SwiftGen` does two things:
1. parse some input files (xcassets, storyboards...) into a context
2. run this context on some stencil files (provided or not)

I see a use for the second feature on its own.
`SwiftGen` must provide a way to take context data and stencil as input and run all of this together.
This would allow users to use `SwiftGen` for any kind of input file.

This would make `SwiftGen` a code generator for _any_ non-swift files, as `Sourcery` is a code generator for existing Swift files.

## Proposed solution

Take JSON files as input **and** templates and generate a Swift file (and maybe several if it is possible).  
The idea is not to offer some 'default' stencil like for the and enforce a JSON file format because both will be tighly coupled to what the user wants to do.

The solution was almost done in https://github.com/SwiftGen/SwiftGen/pull/188 but needed some refinements.  
I have started to work on converting this PR to the new design:
- [SwiftGenKit](https://github.com/Liquidsoul/SwiftGenKit/tree/codegen)
- [SwiftGen](https://github.com/Liquidsoul/SwiftGen/tree/codegen)
- [templates](https://github.com/Liquidsoul/templates/tree/codegen)

But before doing any PRs, I want to discuss this with you guys @djbe and @AliSoftware 😃

**Comment by djbe** [comment]
Hey @Liquidsoul,

I've been thinking about this feature, and it's overlap with https://github.com/SwiftGen/SwiftGen/pull/288. Essentially, both are achieving the same thing: parsing data to provide a context.

We could write a plain `data` parser that provides the following things for each parsed file:
- name of the file
- path to the file (relative to search directory)
- file extension (or mime type)
- data: this is what this issue covers, simply loading the data into a dict/array
- metadata: this is what the plist issue covers, it provides meta information about the types in the data structure

This way, we'd be able to cover all cases, and for some, provide templates (info.plist for example).

**Comment by hebertialmeida** [comment]
Check out this https://github.com/hebertialmeida/ModelGen, it is built on top of SwiftGenKit and Stencil with JSON Schema concept.

**Comment by djbe** [comment]
Implemented by https://github.com/SwiftGen/SwiftGen/pull/379.
