### ISSUE TITLE
Parser protocol

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGenKit#39]
We should unify the interface of the parsers to one common protocol, that they should all support. This will be needed when we eventually want to support a plugin system.

I propose something like the following:

```swift
public protocol Parser {
  init(options: [String: Any])

  func parseFile(at path: Path) throws
  func parseFiles(at paths: [Path]) throws
  func stencilContext() -> [String: Any]
  /// This callback will be called when a Parser want to emit a diagnostics message
  /// You can set this on the usage-site to a closure that prints the diagnostics in any way you see fit
  /// Arguments are (message, file, line)
  var warningHandler: (String, String, UInt) -> Void { get set }
}

public extension Parser {
  func parseFiles(at paths: [Path]) throws {
    for path in paths {
      try parseFile(at: path)
    }
  }
  var waningHandler: (String, String, UInt) -> Void = { (_,_,_) in }
}
```

Missing from this is a way to pass parameters (not template parameters) to the parser implementations. Maybe an `options` dictionary?

**Comment by AliSoftware** [comment]
Edited to add the `warningHandler` we talked about in https://github.com/SwiftGen/SwiftGenKit/pull/40#discussion_r118850329

**Comment by djbe** [comment]
Hmmm, shouldn't that be the other way around? The `Parser` receives a `warningHandler` from the main app, and calls it when needed? (and thus move the `warningHandler` to the `init`)

**Comment by AliSoftware** [comment]
How is that the other way around? Sure I didn't add it to the init (because I feel that handler should be optional, thus the default implementation for it) but the way I've written it it's stiff the main app which provides the warningHandler to the parser as you describe, right? (sorry, I edited the comment once again I forgot to add `{ set }` for that property)

```swift
class FooParser: Parser { … }

let p = FooParser(options: [])
p.warningHandler = { (message, file, line) in print("\(file):\(line): warning: \(message)" }
p.parseFile(at: somePath)
let ctx = p.stencilContext()
```

**Comment by djbe** [comment]
A reason to pass the `warningHandler` in `init`, is because it might be needed there. For example with the colors parser(s), should any of those register a duplicate extension, that'll happen during init:
https://github.com/SwiftGen/SwiftGenKit/blob/master/Sources/Parsers/ColorsFileParser.swift#L49
