### ISSUE TITLE
Cleanup (remove) old stuff

### ISSUE THREAD

**Issue by djbe** [SwiftGen/SwiftGenKit#5]
Refs: https://github.com/AliSoftware/SwiftGen/issues/244

### Colors ###

- `enumName`: has been replaced by `param.enumName`, should provide default value.
- `rgb` and `rgba` (for each color): can be composed from the other components.

### Fonts ###

- `enumName`: has been replaced by `param.enumName`, should provide default value.
- `fontName` (for each font): has been replaced by the `name` property.

### Images ###

- `enumName`: has been replaced by `param.enumName`, should provide default value.
- `images`: just old, `catalogs` contains the structured information.

### Storyboards ###

- `extraImports`: replaced by `modules` (https://github.com/AliSoftware/SwiftGen/pull/243)
- `sceneEnumName`: has been replaced by `param. sceneEnumName`, should provide default value.
- `segueEnumName`: has been replaced by `param. segueEnumName `, should provide default value.template using Stencil.
- For each `scene`:
  - `isBaseViewController`: removed. You can replace it with a test for `baseType == "ViewController"`.

### Strings ###

- `enumName`: has been replaced by `param.enumName`, should provide default value.
- `strings` and `structuredStrings`: replaced by `tables` array, where each table has a structured `levels` property.
- `tableName`: replaced by `tables` array, where each table has a `name` property.
- for each `level`:
  - `subenums`: renamed to `children`.
- for each `string`:
  - `keytail`: renamed to `name`.
  - `params` structure with the `names`, `typednames`, `types`, `count` and `declarations` arrays: removed.
  - These have been replaced by `types` which is an array of types. The previous variables
 can now be reconstructed using template tags now that Stencil has become more powerful.

**Comment by djbe** [comment]
Note: the templates have all ben refactored to not use these properties anymore. The only remaining change that hasn't been done yet (in the templates) is to use `params` as an array instead of `params.types`.

**Comment by djbe** [comment]
Added some more deprecated variables (and their replacements), see PR #13. Will add the new documentation to the wiki.

**Comment by AliSoftware** [comment]
New depreciation to add: the `fontName` could be renamed just `name` for consistency?

**Comment by djbe** [comment]
Sure, I'll make a PR for this later.

**Comment by djbe** [comment]
Closed with the release of 1.1.0

**Comment by djbe** [comment]
With the release of 1.1.0, we can now delete all these variables 🎉
